// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnZgK2W13QFgSw2zC5RGmGD6ReK-7VVLU',
    appId: '1:167140538305:android:12c1cb892a801effe22140',
    messagingSenderId: '167140538305',
    projectId: 'selfcare-notes-40d2f',
    databaseURL: 'https://selfcare-notes-40d2f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'selfcare-notes-40d2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0seKeI69_1cpdI6FBaWmZ52ufOFVrCXs',
    appId: '1:167140538305:ios:896306f97efab603e22140',
    messagingSenderId: '167140538305',
    projectId: 'selfcare-notes-40d2f',
    databaseURL: 'https://selfcare-notes-40d2f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'selfcare-notes-40d2f.appspot.com',
    iosClientId: '167140538305-t8thnkf0p9ips5uqonkln4j592l3gece.apps.googleusercontent.com',
    iosBundleId: 'com.ditow.selfcarenotes',
  );
}
